---
apiVersion: v1
kind: Namespace
metadata:
  name: openwebui
  labels:
    app.kubernetes.io/name: openwebui
    images/dockerhub: "true"
  annotations:
    # Opt in to Chaos Mesh experiments (controller-manager enableFilterNamespace)
    chaos-mesh.org/inject: enabled
