---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: synology
  labels:
    blueprints.goauthentik.io/instantiate: "true"
context: {}
entries:
  # Application for Synology (Bookmark)
  - model: authentik_core.application
    state: present
    identifiers:
      slug: "synology"
    attrs:
      name: "Synology DSM"
      slug: "synology"
      group: "Infrastructure"
      meta_launch_url: "https://diskstation.apocrathia.com:5001"
      open_in_new_tab: true
      icon: "https://gitlab.com/Apocrathia/homelab/-/raw/main/flux/manifests/03-services/authentik/blueprints/icons/synology.svg"
      meta_description: "Synology DiskStation"
      meta_publisher: "Synology"

  # Admins group binding (app access)
  - model: authentik_policies.policybinding
    state: present
    identifiers:
      target: !Find [authentik_core.application, [slug, "synology"]]
      group: !Find [authentik_core.group, [name, "admins"]]
    attrs:
      order: 10
