---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: gitlab-commit-status
  namespace: flux-system
spec:
  type: gitlab
  address: https://gitlab.com/67295640
  secretRef:
    name: gitlab-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: gitlab-deployments
  namespace: flux-system
spec:
  providerRef:
    name: gitlab-commit-status
  eventSources:
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
      namespace: "*"
