---
stages:
  - test
  - verify
  - deploy
  # - renovate

include:
  # - local: .gitlab/renovate.gitlab-ci.yml
  - local: .gitlab/chart-tag.gitlab-ci.yml
  - local: .gitlab/kustomize-diff.gitlab-ci.yml
  - local: .gitlab/scorecard.gitlab-ci.yml
  - local: .gitlab/pages.gitlab-ci.yml
  - local: .gitlab/tofu.gitlab-ci.yml
  # Security scanning
  - local: .gitlab/gitleaks.gitlab-ci.yml
  - local: .gitlab/kube-linter.gitlab-ci.yml
  - local: .gitlab/trivy.gitlab-ci.yml
  - local: .gitlab/shellcheck.gitlab-ci.yml
  - local: .gitlab/semgrep.gitlab-ci.yml
