---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      # renovate: datasource=helm registryUrl=https://kubernetes-sigs.github.io/external-dns depName=external-dns
      version: "1.21.1"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/home-operations/external-dns-unifi-webhook
          # renovate: datasource=docker depName=ghcr.io/home-operations/external-dns-unifi-webhook
          tag: "0.10.12"
        env:
          - name: UNIFI_HOST
            value: "https://10.100.1.1"
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: unifi-dns-secrets
                key: UNIFI_API_KEY
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
      - service
    txtOwnerId: main
    txtPrefix: "k8s.main.%{record_type}-"
    domainFilters:
      - apocrathia.com
    excludeDomains:
      - tailnet.apocrathia.com
    serviceMonitor:
      enabled: true
