---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: skyscraper-secrets
  namespace: skyscraper
spec:
  itemPath: "vaults/Secrets/items/skyscraper-secrets"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: skyscraper-smb-credentials
  namespace: skyscraper
spec:
  itemPath: "vaults/Secrets/items/smb-credentials"
