---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/v1.12.3/pkg/machinery/config/schemas/config.schema.json
machine:
  nodeLabels:
    # https://www.robert-jensen.dk/posts/2025/fix-loadbalancer-services-not-working-on-single-node-talos-kubernetes-cluster/
    node.kubernetes.io/exclude-from-external-load-balancers: ""
    $patch: delete
  certSANs:
    - "10.100.1.80"
    - "10.100.1.8"
    - "talos-01.apocrathia.com"
    - "talos-01.services.apocrathia.com"
    - "kubernetes.apocrathia.com"
    - "127.0.0.1"
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-01
auto: off # yamllint disable-line rule:truthy
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth0
addresses:
  - address: 10.100.1.80/24
routes:
  - gateway: 10.100.1.1
