---
- name: Configure packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - packages

- name: Configure terminfo
  ansible.builtin.import_tasks: terminfo.yml
  tags:
    - terminfo

- name: Configure system
  ansible.builtin.import_tasks: system.yml
  tags:
    - system

- name: Configure network
  ansible.builtin.import_tasks: network.yml
  tags:
    - network

- name: Configure user
  ansible.builtin.import_tasks: user.yml
  tags:
    - user
