#!/usr/bin/env python3
"""Sync harness surfaces from `.agents/` sidecars.

Loads `_harnesses.json` sidecars, generates script-owned transforms (Phase B:
Prime ``APPEND_SYSTEM.md``), fails closed if required sidecars are missing or
an enabled transform is not implemented.
`--check` (default) and `--write` are mutually exclusive.

Exit 0 when clean / written, 1 on drift or missing sidecars, 2 on bad CLI.
Stdlib only; safe for hooks.
"""

from __future__ import annotations

import json
import os
import re
import sys

GENERATED_COMMENT = "<!-- Generated by sync_surfaces.py; do not edit by hand. -->"
MARKER_FILE_CONTENT = "generated by sync_surfaces.py\n"
CURSOR_ONLY_START = "<!-- cursor-only start -->"
CURSOR_ONLY_END = "<!-- cursor-only end -->"

# AGENTS.md Always in force links voice (context) instead of general.md.
AGENTS_ALWAYS_ON_ALLOW_OMIT = frozenset({"general"})

# Match [text](url). Supports angle-bracket destinations (<url>) and
# bare destinations that may contain one level of balanced parentheses.
_MD_LINK_RE = re.compile(
    r"\[([^\]]*)\]\("
    r"(?:<([^>]*)>(\s+(?:\"[^\"]*\"|'[^']*'))?|([^()]*(?:\([^()]*\)[^()]*)*))"
    r"\)"
)
# Match reference-style link definitions: [label]: url "optional title"
# Accepts quoted (double/single) and parenthesized title forms.
# Excludes footnote definitions ([^label]: ...).
_MD_REF_DEF_RE = re.compile(
    r"(?m)^( {0,3}\[[^\^\]]*\]:\s*)(<[^>]*>|[^\s]+)(\s+(?:\"[^\"]*\"|'[^']*'|\([^)]*\)))?[ \t]*$"
)
_ALWAYS_APPLY_TRUE_RE = re.compile(
    r"(?m)^alwaysApply:\s*(?:true|True|TRUE)\s*(?:#.*)?$"
)
_AGENTS_RULE_LINK_RE = re.compile(
    r"\]\((?:\./)?\.agents/rules/([^)/]+?)\.md(?:#[^)]*)?\)"
)

# Links to .agents/context/voice.md (substitute for the general rule).
_AGENTS_CONTEXT_LINK_RE = re.compile(
    r"\]\((?:\./)?\.agents/context/voice\.md(?:#[^)]*)?\)"
)

# Sentinel: a path that should not exist (orphaned generated output).
_DELETE_SENTINEL = object()


def _find_root(start):
    d = os.path.dirname(os.path.abspath(start))
    while True:
        if os.path.isdir(os.path.join(d, ".git")) or os.path.exists(
            os.path.join(d, "AGENTS.md")
        ):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            raise SystemExit(
                "could not locate repo root (no .git or AGENTS.md found above script)"
            )
        d = parent


ROOT = os.path.realpath(_find_root(__file__))

SIDECAR_REL_PATHS = (
    ".agents/rules/_harnesses.json",
    ".agents/agents/_harnesses.json",
    ".agents/skills/_harnesses.json",
)


def _fail(message: str, code: int = 1) -> None:
    """Print a diagnostic and exit with an integer code."""
    print(message)
    raise SystemExit(code)


def load_sidecars(root: str) -> dict[str, dict]:
    """Load the three required sidecars. Fail closed if any are missing."""
    missing = []
    loaded: dict[str, dict] = {}
    for rel in SIDECAR_REL_PATHS:
        path = os.path.join(root, *rel.split("/"))
        if not os.path.isfile(path):
            missing.append(rel)
            continue
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        if not isinstance(data, dict):
            _fail(f"INVALID {rel}: root must be a JSON object")
        if "mirrors" not in data or not isinstance(data["mirrors"], dict):
            _fail(f"INVALID {rel}: missing mirrors object")
        key = rel.split("/")[1]  # rules | agents | skills
        loaded[key] = data
    if missing:
        for rel in missing:
            print(f"MISSING {rel}")
        print(f"\n{len(missing)} missing sidecar(s).")
        raise SystemExit(1)
    return loaded


def strip_yaml_frontmatter(text: str) -> str:
    """Remove leading YAML frontmatter delimited by --- lines."""
    if not text.startswith("---"):
        return text
    # Allow optional newline right after opening fence.
    if text.startswith("---\n"):
        rest = text[4:]
    elif text.startswith("---\r\n"):
        rest = text[5:]
    else:
        return text
    end = rest.find("\n---\n")
    if end == -1:
        end = rest.find("\n---\r\n")
        if end == -1:
            return text
        return rest[end + len("\n---\r\n") :]
    return rest[end + len("\n---\n") :]


def strip_cursor_only(text: str, *, rule_stem: str | None = None) -> str:
    """Remove ``<!-- cursor-only start -->`` … ``<!-- cursor-only end -->`` regions.

    Fail closed if a start marker has no matching end (would otherwise truncate
    portable always-on text to EOF with a green ``--check``), or if an end
    marker appears without a matching start (would otherwise leak Cursor-only
    prose into APPEND_SYSTEM).
    """
    out: list[str] = []
    pos = 0
    where = f" in {rule_stem}.md" if rule_stem else ""
    while True:
        start = text.find(CURSOR_ONLY_START, pos)
        if start == -1:
            tail = text[pos:]
            if CURSOR_ONLY_END in tail:
                _fail(
                    f"INVALID cursor-only{where}: "
                    f"unmatched {CURSOR_ONLY_END!r} "
                    f"(missing {CURSOR_ONLY_START!r})"
                )
            out.append(tail)
            break
        # End marker before the next start is also unmatched.
        orphan_end = text.find(CURSOR_ONLY_END, pos)
        if orphan_end != -1 and orphan_end < start:
            _fail(
                f"INVALID cursor-only{where}: "
                f"unmatched {CURSOR_ONLY_END!r} "
                f"(missing {CURSOR_ONLY_START!r})"
            )
        out.append(text[pos:start])
        end = text.find(CURSOR_ONLY_END, start + len(CURSOR_ONLY_START))
        if end == -1:
            _fail(
                f"INVALID cursor-only{where}: "
                f"unclosed {CURSOR_ONLY_START!r} (missing {CURSOR_ONLY_END!r})"
            )
        nested = text.find(CURSOR_ONLY_START, start + len(CURSOR_ONLY_START), end)
        if nested != -1:
            _fail(
                f"INVALID cursor-only{where}: "
                f"nested {CURSOR_ONLY_START!r} inside a cursor-only region"
            )
        pos = end + len(CURSOR_ONLY_END)
        # Drop a single following newline so wrapping does not leave blanks.
        if pos < len(text) and text[pos] == "\r":
            pos += 1
        if pos < len(text) and text[pos] == "\n":
            pos += 1
    return "".join(out)


def rewrite_relative_links(body: str, source_dir: str, dest_dir: str) -> str:
    """Rewrite relative Markdown links so they resolve from ``dest_dir``.

    ``source_dir`` and ``dest_dir`` are repo-relative POSIX directory paths
    (no trailing slash). Absolute URL schemes, root-absolute paths, and
    fragment-only links are left unchanged. Links inside code spans and fenced
    code blocks are not rewritten.
    """
    # Mask code spans and fenced blocks so links inside them are not rewritten.
    _code_spans: list[str] = []

    def _mask(m: re.Match[str]) -> str:
        _code_spans.append(m.group(0))
        return f"\x00{len(_code_spans) - 1}\x00"

    # Match fence length (≥3) so a longer outer fence can wrap nested
    # shorter fences without unmasking the inner block early.
    body = re.sub(r"(`{3,}).*?\1", _mask, body, flags=re.DOTALL)
    body = re.sub(r"(~{3,}).*?\1", _mask, body, flags=re.DOTALL)
    body = re.sub(r"``[^`]*``", _mask, body)
    body = re.sub(r"`[^`]*`", _mask, body)

    def repl(match: re.Match[str]) -> str:
        label = match.group(1)
        # group(2) is angle-bracket destination; group(4) is bare destination.
        url = match.group(2)
        if url is not None:
            wrapped = True
            title = match.group(3) or ""
        else:
            wrapped = False
            url = match.group(4)
            title = ""
        rewritten = _rewrite_one_url(url, source_dir, dest_dir)
        if wrapped:
            return f"[{label}](<{rewritten}>{title})"
        return f"[{label}]({rewritten})"

    body = _MD_LINK_RE.sub(repl, body)

    def ref_repl(match: re.Match[str]) -> str:
        prefix = match.group(1)
        url = match.group(2)
        title = match.group(3) or ""
        # Strip angle brackets from the URL before rewriting.
        had_brackets = url.startswith("<") and url.endswith(">")
        if had_brackets:
            url = url[1:-1]
        rewritten = _rewrite_one_url(url, source_dir, dest_dir)
        # Re-wrap in angle brackets if the original had them or the
        # destination contains whitespace so Markdown treats it as one.
        if had_brackets or " " in rewritten:
            rewritten = f"<{rewritten}>"
        return f"{prefix}{rewritten}{title}"

    body = _MD_REF_DEF_RE.sub(ref_repl, body)

    # Restore masked code spans and fenced blocks.
    def _restore(m: re.Match[str]) -> str:
        return _code_spans[int(m.group(1))]

    body = re.sub(r"\x00(\d+)\x00", _restore, body)
    return body


def _rewrite_one_url(url: str, source_dir: str, dest_dir: str) -> str:
    raw = url.strip()
    if not raw:
        return url
    if raw.startswith(("#", "/")):
        return url
    # Any absolute URI scheme (http, https, ftp, mailto, custom) — leave as-is.
    if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", raw):
        return url
    # Optional link title: path "title" or path 'title'
    title_suffix = ""
    path_part = raw
    for quote in ('"', "'"):
        marker = f" {quote}"
        idx = raw.find(marker)
        if idx != -1 and raw.endswith(quote):
            path_part = raw[:idx]
            title_suffix = raw[idx:]
            break

    fragment = ""
    if "#" in path_part:
        path_part, frag = path_part.split("#", 1)
        fragment = "#" + frag
    if not path_part:
        return url

    # Unescape Markdown backslash escapes (e.g. \( → (, \\ → \) before path
    # processing so escaped punctuation is not treated as an OS separator.
    path_part = re.sub(r"\\(.)", r"\1", path_part)

    joined = os.path.normpath(os.path.join(source_dir, path_part)).replace("\\", "/")
    new_rel = os.path.relpath(joined, dest_dir).replace("\\", "/")
    if new_rel.startswith("/"):
        # Should not happen with relative dest_dir; keep original rather than
        # emit a root-absolute path.
        return url
    return new_rel + fragment + title_suffix


def process_rule_body(
    text: str, source_dir: str, dest_dir: str, *, rule_stem: str | None = None
) -> str:
    """Frontmatter strip, cursor-only strip, then destination-aware link rewrite."""
    body = strip_yaml_frontmatter(text)
    body = strip_cursor_only(body, rule_stem=rule_stem)
    body = rewrite_relative_links(body, source_dir, dest_dir)
    # Trim blank lines only; keep leading indentation on the first content line.
    body = body.lstrip("\n").rstrip() + "\n"
    return body


# Allowed directory for generated APPEND_SYSTEM output.
_APPEND_SYSTEM_DIR = ".prime/agent/"


def _validate_append_system_path(path: str) -> str:
    """Return the normalised path or fail if it escapes the allowed directory.

    Only top-level files under ``.prime/agent/`` are accepted — no nested
    subdirectories and no ``.generated`` suffix (reserved for marker files).
    """
    norm = os.path.normpath(path.replace("\\", "/")).replace(os.sep, "/")
    if not norm.startswith(_APPEND_SYSTEM_DIR):
        _fail(
            f"INVALID append_system: path must be under {_APPEND_SYSTEM_DIR} (got {path})"
        )
    remainder = norm[len(_APPEND_SYSTEM_DIR) :]
    if "/" in remainder:
        _fail(
            f"INVALID append_system: path must be a top-level file under "
            f"{_APPEND_SYSTEM_DIR} (got {path})"
        )
    if norm.endswith(".generated"):
        _fail(
            f"INVALID append_system: path must not end with '.generated' "
            f"(reserved for marker files; got {path})"
        )
    if not norm.endswith(".md"):
        _fail(f"INVALID append_system: path must end with .md (got {path})")
    return norm


def build_append_system(root: str, append: dict) -> dict[str, str]:
    """Build expected content for APPEND_SYSTEM.md and its .generated marker."""
    path = append.get("path")
    if not path or not isinstance(path, str):
        _fail("INVALID append_system: enabled but path missing")
    path = _validate_append_system_path(path)
    rules = append.get("rules")
    if not isinstance(rules, list) or not rules:
        _fail("INVALID append_system: enabled but rules missing or empty")
    if not all(isinstance(r, str) and r for r in rules):
        _fail("INVALID append_system: rules must be a list of non-empty strings")

    source_dir = ".agents/rules"
    dest_dir = os.path.dirname(path.replace("\\", "/")) or "."
    parts: list[str] = [GENERATED_COMMENT, ""]
    for stem in rules:
        rel = f"{source_dir}/{stem}.md"
        rule_path = os.path.join(root, *rel.split("/"))
        if not os.path.isfile(rule_path):
            _fail(f"MISSING {rel}")
        with open(rule_path, encoding="utf-8") as fh:
            raw = fh.read()
        body = process_rule_body(raw, source_dir, dest_dir, rule_stem=stem)
        parts.append(f"<!-- rule: {stem} -->")
        parts.append("")
        parts.append(body.rstrip("\n"))
        parts.append("")
    content = "\n".join(parts)
    if not content.endswith("\n"):
        content += "\n"
    marker_rel = path + ".generated"
    return {
        path: content,
        marker_rel: MARKER_FILE_CONTENT,
    }


def scan_always_apply_rules(root: str) -> list[str]:
    """Basenames (sans .md) of rules with ``alwaysApply: true`` frontmatter."""
    rules_dir = os.path.join(root, ".agents", "rules")
    if not os.path.isdir(rules_dir):
        return []
    stems: list[str] = []
    for name in sorted(os.listdir(rules_dir)):
        if not name.endswith(".md"):
            continue
        path = os.path.join(rules_dir, name)
        if not os.path.isfile(path):
            continue
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        if not text.startswith("---"):
            continue
        end = text.find("\n---\n", 3)
        if end == -1:
            continue
        front = text[3:end]
        if _ALWAYS_APPLY_TRUE_RE.search(front):
            stems.append(name[: -len(".md")])
    return stems


def parse_agents_always_on_rule_links(root: str) -> set[str]:
    """Rule basenames linked from the AGENTS.md Always in force section."""
    path = os.path.join(root, "AGENTS.md")
    if not os.path.isfile(path):
        return set()
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    marker = "## Always in force"
    start = text.find(marker)
    if start == -1:
        return set()
    rest = text[start + len(marker) :]
    next_h2 = rest.find("\n## ")
    section = rest if next_h2 == -1 else rest[:next_h2]
    # Mask HTML comments and inline code so links inside them are not counted.
    section = re.sub(r"<!--.*?-->", "", section, flags=re.DOTALL)
    section = re.sub(r"`[^`]*`", "", section)
    return set(_AGENTS_RULE_LINK_RE.findall(section))


def _read_agents_always_on_section(root: str) -> str:
    """Return the text of the AGENTS.md 'Always in force' section (empty if absent)."""
    path = os.path.join(root, "AGENTS.md")
    if not os.path.isfile(path):
        return ""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    marker = "## Always in force"
    start = text.find(marker)
    if start == -1:
        return ""
    rest = text[start + len(marker) :]
    next_h2 = rest.find("\n## ")
    section = rest if next_h2 == -1 else rest[:next_h2]
    # Mask HTML comments and inline code so links inside them are not counted.
    section = re.sub(r"<!--.*?-->", "", section, flags=re.DOTALL)
    section = re.sub(r"`[^`]*`", "", section)
    return section


def check_always_on_consistency(root: str, append: dict) -> list[str]:
    """Return one-line reason strings when always_on / rules / disk / AGENTS drift.

    ``always_on`` is the source of truth. ``rules`` must match it as a set
    (order may differ). Disk ``alwaysApply: true`` must match ``always_on``.
    AGENTS.md Always in force rule links must match ``always_on`` except for
    intentional omissions in ``AGENTS_ALWAYS_ON_ALLOW_OMIT``. An allowed
    omission (e.g. ``general``) must still have a documented substitute:
    AGENTS.md must link ``.agents/context/voice.md``.
    """
    reasons: list[str] = []
    always_on = append.get("always_on")
    rules = append.get("rules")
    if not isinstance(always_on, list) or not all(
        isinstance(x, str) and x for x in always_on
    ):
        return ["STALE append_system.always_on (invalid or missing list)"]
    if not isinstance(rules, list) or not all(isinstance(x, str) and x for x in rules):
        return ["STALE append_system.rules (invalid or missing list)"]

    if len(set(always_on)) != len(always_on):
        return ["STALE append_system.always_on (duplicate stems)"]
    if len(set(rules)) != len(rules):
        return ["STALE append_system.rules (duplicate stems)"]
    always_set = set(always_on)
    rules_set = set(rules)
    if rules_set != always_set:
        reasons.append("STALE append_system.rules (differs from always_on)")

    disk = set(scan_always_apply_rules(root))
    if disk != always_set:
        missing = sorted(disk - always_set)
        extra = sorted(always_set - disk)
        if missing:
            reasons.append(
                "STALE append_system.always_on (missing alwaysApply: "
                + ", ".join(missing)
                + ")"
            )
        if extra:
            reasons.append(
                "STALE append_system.always_on (not alwaysApply on disk: "
                + ", ".join(extra)
                + ")"
            )

    agents_links = parse_agents_always_on_rule_links(root)
    # always_on entries omitted from AGENTS with allowlist (e.g. general).
    omitted = always_set - agents_links
    unexpected_omit = sorted(omitted - AGENTS_ALWAYS_ON_ALLOW_OMIT)
    if unexpected_omit:
        reasons.append(
            "STALE AGENTS.md Always in force (missing rule links: "
            + ", ".join(unexpected_omit)
            + ")"
        )
    # An allowed omission must still have a documented substitute: AGENTS.md
    # must link .agents/context/voice.md for each allowlisted stem.
    allowed_omit = sorted(omitted & AGENTS_ALWAYS_ON_ALLOW_OMIT)
    if allowed_omit and not _AGENTS_CONTEXT_LINK_RE.findall(
        _read_agents_always_on_section(root)
    ):
        reasons.append(
            "STALE AGENTS.md Always in force (allowed omission without "
            "voice.md substitute: " + ", ".join(allowed_omit) + ")"
        )
    extra_agents = sorted(agents_links - always_set)
    if extra_agents:
        reasons.append(
            "STALE AGENTS.md Always in force (rule links not in always_on: "
            + ", ".join(extra_agents)
            + ")"
        )
    return reasons


def _scan_orphaned_generated(
    root: str, expected: dict[str, object]
) -> dict[str, object]:
    """Detect `.generated`-marked files in the allowed directory that are orphans.

    A marker file is an orphan when it contains ``MARKER_FILE_CONTENT`` and its
    companion (the path without the ``.generated`` suffix) is not in *expected*.
    The marker and its companion are returned with ``_DELETE_SENTINEL`` so that
    ``--check`` reports them as stale and ``--write`` removes them.
    """
    orphans: dict[str, object] = {}
    scan_dir = os.path.normpath(os.path.join(root, *_APPEND_SYSTEM_DIR.split("/")))
    if not os.path.isdir(scan_dir):
        return orphans
    for dirpath, _dirnames, filenames in os.walk(scan_dir):
        for name in sorted(filenames):
            if not name.endswith(".generated"):
                continue
            marker_path = os.path.join(dirpath, name)
            # Only scan top-level files (subdirectories may belong to other
            # transforms such as .prime/agent/prompts/).
            if dirpath != scan_dir:
                continue
            marker_rel = os.path.relpath(marker_path, root).replace(os.sep, "/")
            if marker_rel in expected:
                continue
            if not os.path.isfile(marker_path) or os.path.islink(marker_path):
                continue
            with open(marker_path, encoding="utf-8") as fh:
                if fh.read() != MARKER_FILE_CONTENT:
                    continue
            companion_rel = marker_rel[: -len(".generated")]
            orphans[marker_rel] = _DELETE_SENTINEL
            if companion_rel not in expected and companion_rel.endswith(".md"):
                orphans[companion_rel] = _DELETE_SENTINEL
    return orphans


def plan_transforms(
    sidecars: dict[str, dict], root: str | None = None
) -> dict[str, str]:
    """Return rel_path -> expected content for script-owned transforms.

    Enabled mirrors without a generator fail closed. Enabled ``append_system``
    builds ``APPEND_SYSTEM.md`` plus the adjacent ``.generated`` marker.
    """
    if root is None:
        root = ROOT

    unimplemented: list[str] = []
    for surface, data in sidecars.items():
        mirrors = data.get("mirrors") or {}
        if not isinstance(mirrors, dict):
            _fail(f"INVALID {surface}: mirrors must be an object")
        for harness, cfg in mirrors.items():
            if not isinstance(cfg, dict):
                _fail(
                    f"INVALID {surface}.mirrors.{harness}: "
                    "mirror entry must be a JSON object"
                )
            if cfg.get("enabled"):
                unimplemented.append(f"{surface}.mirrors.{harness}")

    if unimplemented:
        for item in unimplemented:
            print(f"UNIMPLEMENTED {item}")
        print(
            f"\n{len(unimplemented)} enabled transform(s) not implemented "
            "(enable only after a later phase lands the generator)."
        )
        raise SystemExit(1)

    expected: dict[str, str | object] = {}
    rules = sidecars.get("rules", {})
    append = rules.get("append_system")
    if append is not None:
        if not isinstance(append, dict):
            _fail("INVALID rules append_system: must be an object")
        if "enabled" not in append:
            _fail("INVALID append_system: enabled key is required")
        if not isinstance(append["enabled"], bool):
            _fail("INVALID append_system: enabled must be a boolean")
        if append.get("enabled"):
            path = append.get("path")
            if not path or not isinstance(path, str):
                _fail("INVALID append_system: enabled but path missing")
            if "rules" not in append or "always_on" not in append:
                _fail("INVALID append_system: enabled but rules/always_on missing")
            consistency = check_always_on_consistency(root, append)
            if consistency:
                for line in consistency:
                    print(line)
                print(f"\n{len(consistency)} always_on consistency error(s).")
                raise SystemExit(1)
            expected.update(build_append_system(root, append))
        else:
            # Disabled: detect orphaned generated output so --check fails and
            # --write removes stale files instead of silently dropping ownership.
            # Only schedule deletion when a valid .generated marker proves the
            # file was script-owned; never delete hand-authored content.
            path = append.get("path")
            if isinstance(path, str) and path:
                path = _validate_append_system_path(path)
                marker_rel = path + ".generated"
                marker_path = os.path.join(root, *marker_rel.split("/"))
                marker_valid = False
                if os.path.isfile(marker_path) and not os.path.islink(marker_path):
                    with open(marker_path, encoding="utf-8") as fh:
                        marker_valid = fh.read() == MARKER_FILE_CONTENT
                if marker_valid:
                    for rel in (path, marker_rel):
                        full = os.path.join(root, *rel.split("/"))
                        # Include dangling symlinks: isfile() is false for them,
                        # but later stale/delete logic already treats islink.
                        if os.path.isfile(full) or os.path.islink(full):
                            expected[rel] = _DELETE_SENTINEL
    # Detect orphaned generated output from retargeted or disabled transforms.
    expected.update(_scan_orphaned_generated(root, expected))
    return expected


def collect_stale(root: str, expected: dict[str, str | object]) -> list[str]:
    """Return owned relative paths whose on-disk content drifts from expected.

    A ``_DELETE_SENTINEL`` value means the file should not exist; it is stale
    when present on disk (orphaned generated output after a transform is disabled).
    """
    stale: list[str] = []
    for rel, want in sorted(expected.items()):
        path = os.path.join(root, *rel.split("/"))
        if want is _DELETE_SENTINEL:
            if os.path.isfile(path) or os.path.islink(path):
                stale.append(rel)
            continue
        if os.path.islink(path):
            stale.append(rel)
            continue
        if not os.path.isfile(path):
            stale.append(rel)
            continue
        with open(path, encoding="utf-8") as fh:
            got = fh.read()
        if got != want:
            stale.append(rel)
    return stale


def _check_symlink_parents(path: str, rel: str, root: str) -> None:
    """Fail if any parent directory of *path* (up to *root*) is a symlink."""
    # Walk from root down to the file's parent directory.
    parent = os.path.dirname(path)
    parts = []
    cur = parent
    while cur != root and os.path.dirname(cur) != cur:
        parts.append(cur)
        cur = os.path.dirname(cur)
    for p in reversed(parts):
        if os.path.islink(p):
            _fail(
                f"REFUSING to write {rel}: parent directory "
                f"{os.path.relpath(p, root)} is a symlink"
            )


def write_expected(root: str, expected: dict[str, str | object]) -> None:
    # Pre-validate all write destinations before any mutation so a
    # symlink refusal on a later-sorting path prevents deletion of
    # earlier-sorting orphans.
    for rel, content in sorted(expected.items()):
        if content is _DELETE_SENTINEL:
            continue
        path = os.path.join(root, *rel.split("/"))
        if os.path.islink(path):
            _fail(
                f"REFUSING to write {rel}: existing path is a symlink "
                f"(would follow and overwrite the target)"
            )
        # Reject directories and other non-regular objects before any writes.
        # Marker paths skip the hand-authored isfile guard below; a directory
        # at the destination would pass that skip and fail mid-write.
        if os.path.lexists(path) and not os.path.isfile(path):
            _fail(
                f"REFUSING to write {rel}: existing path is not a regular file "
                f"(would fail mid-write and leave earlier destinations mutated)"
            )
        _check_symlink_parents(path, rel, root)
        # Refuse to overwrite a hand-authored file without a valid on-disk
        # marker. Require the marker to already exist even when this pass also
        # plans to write it — otherwise first-time generation can claim user
        # content by creating the marker after the overwrite.
        if not rel.endswith(".generated") and os.path.isfile(path):
            marker_path = path + ".generated"
            marker_valid = False
            if os.path.isfile(marker_path) and not os.path.islink(marker_path):
                with open(marker_path, encoding="utf-8") as fh:
                    marker_valid = fh.read() == MARKER_FILE_CONTENT
            if not marker_valid:
                _fail(
                    f"REFUSING to write {rel}: existing file has no valid "
                    f".generated marker (would overwrite hand-authored content)"
                )
    # Execute all mutations after validation passes.
    # Process writes before deletes so a failed write does not leave
    # the old output already removed.
    writes = [(r, c) for r, c in sorted(expected.items()) if c is not _DELETE_SENTINEL]
    deletes = [(r, c) for r, c in sorted(expected.items()) if c is _DELETE_SENTINEL]
    for rel, content in writes:
        path = os.path.join(root, *rel.split("/"))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        # Write atomically: temp file then rename, so an interrupted
        # --write never leaves a partial file on disk.
        import uuid

        tmp_path = path + "." + uuid.uuid4().hex + ".tmp"
        with open(tmp_path, "x", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        os.replace(tmp_path, path)
    for rel, content in deletes:
        path = os.path.join(root, *rel.split("/"))
        _check_symlink_parents(path, rel, root)
        if os.path.isfile(path) or os.path.islink(path):
            os.remove(path)


def parse_args(argv: list[str]) -> str:
    """Return mode: 'check' or 'write'. Exit 2 on bad flags."""
    check = "--check" in argv
    write = "--write" in argv
    if check and write:
        print("error: --check and --write are mutually exclusive")
        raise SystemExit(2)
    unknown = [a for a in argv if a not in {"--check", "--write"}]
    if unknown:
        print(f"error: unknown argument(s): {' '.join(unknown)}")
        raise SystemExit(2)
    if write:
        return "write"
    return "check"


def main() -> int:
    try:
        mode = parse_args(sys.argv[1:])
        sidecars = load_sidecars(ROOT)
        expected = plan_transforms(sidecars, ROOT)
        if mode == "write":
            write_expected(ROOT, expected)
    except SystemExit as exc:
        code = exc.code
        if isinstance(code, int):
            return code
        if code is None:
            return 0
        print(code)
        return 1

    if mode == "write":
        print("Harness surfaces written.")
        return 0

    stale = collect_stale(ROOT, expected)
    if stale:
        for rel in stale:
            print(f"STALE {rel}")
        print(f"\n{len(stale)} stale path(s).")
        return 1
    print("Harness surfaces are in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
