---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossview

namespace: crossview

resources:
  - namespace.yaml
  - secret.yaml
  - helmrelease.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authentik-blueprint-crossview
    namespace: crossview
    files:
      - crossview.yaml=authentik-blueprint.yaml

labels:
  - includeSelectors: true
    pairs:
      authentik_blueprint: "true"
