---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: mcp-server
  namespace: prometheus-system
spec:
  name: mcp-server
  instanceName: kube-prometheus-stack-grafana
  role: Admin
  isDisabled: false
  tokens:
    - name: mcp-server-token
      secretName: mcp-server-token
