---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: alert-agent-invoke

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - grafana.yaml

configMapGenerator:
  - name: alert-agent-invoke-scripts
    namespace: agent-tasks
    files:
      - alert-template.md=prompts/alert-template.md
      - server.py=src/server.py
      - pyproject.toml=src/pyproject.toml
      - uv.lock=src/uv.lock
