---
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: flux
  namespace: mcp-flux
  labels:
    app.kubernetes.io/name: flux
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/part-of: artificial-intelligence
    app.kubernetes.io/managed-by: flux
spec:
  transportType: http
  httpTransport:
    path: /mcp
    targetPort: 8080
  deployment:
    # renovate: datasource=docker registryUrl=https://ghcr.io depName=controlplaneio-fluxcd/flux-operator-mcp
    image: ghcr.io/controlplaneio-fluxcd/flux-operator-mcp:v0.59.0@sha256:ca1b36b93bb8fa22eb941af690c1788c5eddc12497eff645452f9710b2c389c0
    port: 8080
    args:
      - serve
      - --transport
      - http
      - --port
      - "8080"
    serviceAccountName: flux-mcp-sa
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
