---
apiVersion: v1
kind: Namespace
metadata:
  name: calibre-web-automated
  labels:
    app.kubernetes.io/name: calibre-web-automated
    app.kubernetes.io/component: media-management
    app.kubernetes.io/part-of: media
    images/dockerhub: "true"
