---
apiVersion: v1
kind: Namespace
metadata:
  name: slskd
  labels:
    app.kubernetes.io/name: slskd
    images/dockerhub: "true"
    # Privileged security context - allows NET_ADMIN capability for VPN
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
