---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: chaos-mesh
  namespace: chaos-mesh
resources:
  - namespace.yaml
  - rbac.yaml
  - helmrelease.yaml
  - push-secret.yaml
  - crossplane.yaml

generatorOptions:
  disableNameSuffixHash: true
