---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mumble-tls
  namespace: mumble
spec:
  commonName: mumble.services.apocrathia.com
  dnsNames:
    - mumble.services.apocrathia.com
    - mumble.apocrathia.com
  duration: 2160h
  renewBefore: 360h
  secretName: mumble-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  subject:
    organizations:
      - Apocrathia
