---
# yaml-language-server: $schema=https://raw.githubusercontent.com/1Password/onepassword-operator/main/config/crd/bases/onepassword.com_onepassworditems.yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: agent-substrate-secrets
  namespace: ate-system
spec:
  # Required fields (same names as Loki/Tempo S3 secrets):
  # - access-key-id
  # - access-key-secret
  itemPath: "vaults/Secrets/items/agent-substrate-secrets"
