---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amp-exporter
  namespace: amp-exporter
  labels:
    app.kubernetes.io/name: amp-exporter
    app.kubernetes.io/component: metrics
spec:
  selector:
    matchLabels:
      app: amp-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
