---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: gaming-pc-node-exporter
  namespace: prometheus-system
  labels:
    release: kube-prometheus-stack
spec:
  staticConfigs:
    - targets:
        - ians-gaming-pc.access.apocrathia.com:9100
      labels:
        job: node
        instance: ians-gaming-pc
        device_type: workstation
  scrapeInterval: 30s
  scrapeTimeout: 10s
  metricsPath: /metrics
  scheme: HTTP
