---
# Talos ServiceAccount that auto-generates credentials for talosctl
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: etcd-defrag
  namespace: kube-system
spec:
  roles:
    - os:admin
