---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane

namespace: crossplane-system

resources:
  - namespace.yaml
  - helmrelease.yaml
  - crossview-secret.yaml
  - crossview-postgres.yaml
  - crossview-helmrelease.yaml
  - provider-opentofu.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authentik-blueprint-crossview
    namespace: crossplane-system
    files:
      - crossview.yaml=authentik-blueprint.yaml

labels:
  - includeSelectors: true
    pairs:
      authentik_blueprint: "true"
