---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: media

resources:
  - acquisitions/archiveteam-warrior
  - acquisitions/bitmagnet
  - acquisitions/lidarr-youtube-downloader
  - acquisitions/pinchflat
  - acquisitions/prowlarr
  - acquisitions/qbittorrent
  - acquisitions/rdt-client
  - acquisitions/sabnzbd
  - acquisitions/zilean
  - management/bazarr
  - management/cleanuparr
  - management/huntarr2
  - management/icloudpd
  - management/immich
  - management/jellyplex-watched
  - management/lidarr
  # - management/maintainerr
  # - management/mixarr
  # - management/ombi
  - management/radarr
  - management/recyclarr
  - management/seerr
  - management/sonarr
  - management/suwayomi
  - management/taggarr
  - management/tracearr
  - management/tdarr
  - management/whisparr
  - management/scripts
  # - servers/audiobookshelf
  - servers/jellyfin
  - servers/komga
  - servers/plex
  - servers/tunarr
