---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: media

resources:
  - acquisitions/archiveteam-warrior
  - acquisitions/bitmagnet
  - acquisitions/lidarr-youtube-downloader
  - acquisitions/prowlarr
  - acquisitions/qbittorrent
  - acquisitions/rdt-client
  - acquisitions/reaparr
  - acquisitions/sabnzbd
  - acquisitions/zilean
  - management/agregarr
  - management/bazarr
  - management/chaptarr
  - management/cleanuparr
  # - management/daps
  # - management/huntarr
  - management/huntarr2
  - management/icloudpd
  - management/immich
  - management/lazylibrarian
  - management/lidarr
  - management/maintainerr
  - management/mylar
  - management/mixarr
  # - management/ombi
  # - management/overseerr
  - management/radarr
  - management/recommendarr
  - management/recyclarr
  - management/seerr
  - management/shinkro
  - management/sonarr
  - management/suwayomi
  - management/taggarr
  - management/tautulli
  - management/tdarr
  - management/whisparr
  - management/scripts
  - servers/audiobookshelf
  - servers/invidious
  # - servers/jellyfin
  - servers/komga
  - servers/plex
  - servers/tunarr
